load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "day-1",
    srcs = glob(["day-1/*.cpp", "day-1/*.h", "io/*.h", "io/*.cpp"]),
)

cc_binary(
    name = "day-2",
    srcs = glob(["day-2/*.cpp", "day-2/*.h", "io/*.h", "io/*.cpp"]),
)

cc_binary(
    name = "day-3",
    srcs = glob(["day-3/*.cpp", "day-3/*.h", "io/*.h", "io/*.cpp"]),
)

cc_binary(
    name = "day-4",
    srcs = glob(["day-4/*.cpp", "day-4/*.h", "io/*.h", "io/*.cpp"]),
)