cc_binary(
    name = "day-1",
    srcs = glob(["day-1/*.cpp", "io/*.h", "io/*.cpp"]),
)

cc_binary(
    name = "day-2",
    srcs = glob(["day-2/*.cpp", "io/*.h", "io/*.cpp"]),
)

cc_binary(
    name = "day-3",
    srcs = glob(["day-3/*.cpp", "io/*.h", "io/*.cpp"]),
)

cc_binary(
    name = "day-4",
    srcs = glob(["day-4/*.cpp", "io/*.h", "io/*.cpp"]),
)

cc_binary(
    name = "day-5",
    srcs = glob(["day-5/*.cpp", "io/*.h", "io/*.cpp"]),
)

cc_binary(
    name = "day-6",
    srcs = glob(["day-6/*.cpp", "io/*.h", "io/*.cpp"]),
)

cc_binary(
    name = "day-7",
    srcs = glob(["day-7/*.cpp", "io/*.h", "io/*.cpp"]),
)

cc_binary(
    name = "day-8",
    srcs = glob(["day-8/*.cpp", "io/*.cpp", "io/*.h"])
)

cc_binary(
    name = "day-9",
    srcs = glob(["day-9/*.cpp", "io/*.cpp", "io/*.h"])
)

cc_binary(
    name = "day-10",
    srcs = glob(["day-10/*.cpp", "io/*.cpp", "io/*.h"])
)

cc_binary(
    name = "day-11",
    srcs = glob(["day-11/*.cpp", "io/*.cpp", "io/*.h"])
)

cc_binary(
    name = "day-12",
    srcs = glob(["day-12/*.cpp", "io/*.cpp", "io/*.h"])
)

cc_binary(
    name = "day-13",
    srcs = glob(["day-13/*.cpp", "io/*.cpp", "io/*.h"])
)